name: StoneFlow Plugin CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: wordpress
          MYSQL_USER: wp
          MYSQL_PASSWORD: wp
          MYSQL_ROOT_PASSWORD: root
        ports: ["3306:3306"]
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, intl
          coverage: none

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Install WP-CLI
        run: |
          curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
          chmod +x wp-cli.phar
          sudo mv wp-cli.phar /usr/local/bin/wp

      - name: Set up WordPress test library and config
        run: |
          git clone --depth=1 --branch=6.5 https://github.com/WordPress/wordpress-develop.git /tmp/wordpress
          bash /tmp/wordpress/tools/local-env/scripts/start.sh
          git clone --depth=1 https://github.com/WordPress/wordpress-develop.git /tmp/wordpress-tests-lib
          bash /tmp/wordpress-tests-lib/tools/install.sh wordpress root '' 127.0.0.1 latest

      - name: Run PHPUnit
        env:
          WP_TESTS_DIR: /tmp/wordpress-tests-lib
        run: |
          vendor/bin/phpunit --configuration phpunit.xml.dist
