name: StoneFlow Plugin CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: wordpress_test
          MYSQL_USER: wordpress
          MYSQL_PASSWORD: wordpress
          MYSQL_ROOT_PASSWORD: wordpress
        ports:
          - 3306:3306
        options: >-
          --name stoneflow-mysql
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      # 1️⃣  Check out the code
      - name: Check out repository
        uses: actions/checkout@v4

      # 2️⃣  Set up PHP 8.2 with all required tools and extensions
      - name: Set up PHP 8.2
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          coverage: none
          tools: composer, phpunit, wp-cli
          extensions: >
            mbstring,
            intl,
            dom,
            xml,
            simplexml,
            xmlwriter,
            curl,
            tokenizer,
            zip

      # 3️⃣  Install Composer dependencies (PHPUnit, PHPCS, etc.)
      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --no-suggest

      # 4️⃣  Install Subversion (required by the WP test-library action)
      - name: Install SVN
        run: sudo apt-get update && sudo apt-get install -y subversion

      # 5️⃣  Download WordPress core and the official PHPUnit test library manually
      - name: Install WordPress test library
        run: |
          git clone --depth=1 https://github.com/WordPress/wordpress-develop.git /tmp/wordpress-develop
          mkdir -p /tmp/wordpress-tests-lib
          cp -r /tmp/wordpress-develop/tests/phpunit/includes /tmp/wordpress-tests-lib
          cp -r /tmp/wordpress-develop/tests/phpunit/data /tmp/wordpress-tests-lib
          cp /tmp/wordpress-develop/wp-tests-config-sample.php /tmp/wordpress-tests-lib/wp-tests-config.php

      # 6️⃣  Run the PHPUnit test suite
      - name: Run PHPUnit
        run: vendor/bin/phpunit --configuration phpunit.xml.dist --testdox
        env:
          WP_TESTS_DIR: /tmp/wordpress-tests-lib

      # 7️⃣  Enforce WordPress coding standards
      - name: Run PHPCS
        run: vendor/bin/phpcs --standard=WordPress stoneflow
