name: StoneFlow Plugin CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: wordpress_test
          MYSQL_USER: wordpress
          MYSQL_PASSWORD: wordpress
          MYSQL_ROOT_PASSWORD: wordpress
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      # 1️⃣  Check out the plugin code
      - uses: actions/checkout@v4

      # 2️⃣  Install PHP 8.2 **and** make sure Composer, PHPUnit & WP-CLI are on PATH
      - name: Set up PHP 8.2
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          coverage: none
          extensions: mbstring, intl
          tools: composer, phpunit, wp-cli   # ← guarantees `composer` & `phpunit` binaries exist

      # 3️⃣  Install Composer dependencies (phpunit, wpcs, …)
      - name: Install Composer deps
        run: composer install --no-interaction --prefer-dist

      # 4️⃣  Download WordPress + its PHPUnit library (one-liner action)
      - name: Set up WordPress test library
        uses: sjinks/setup-wordpress-test-library@v2.1.4   # marketplace action

      # 5️⃣  Run the test suite
      - name: Run PHPUnit
        run: vendor/bin/phpunit --configuration phpunit.xml.dist --testdox
