name: StoneFlow Plugin CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: wordpress
          MYSQL_USER: wp
          MYSQL_PASSWORD: wp
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      # 1️⃣  Pull the repo
      - uses: actions/checkout@v4

      # 2️⃣  Install PHP 8.2 *and* the tools we need
      - name: Set up PHP 8.2 with Composer, PHPUnit, WP-CLI
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, intl
          coverage: none
          tools: composer, phpunit, wp-cli   # ← ensures `composer` and `php` are in PATH

      # 3️⃣  Install plugin dev-dependencies (phpunit, wpcs, …)
      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist

      # 4️⃣  Spin up the official WP test library (downloads WP core + config)
      - name: Set up WordPress test library
        uses: actions/setup-wordpress-test-library@v1
        with:
          wordpress-version: latest          # or '6.5', etc.
          php-version: 8.2

      # 5️⃣  Run the test suite
      - name: Run PHPUnit
        run: vendor/bin/phpunit --configuration phpunit.xml.dist --testdox
