name: StoneFlow Plugin CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: wordpress_test
          MYSQL_USER: wordpress
          MYSQL_PASSWORD: wordpress
          MYSQL_ROOT_PASSWORD: wordpress
        ports:
          - 3306:3306
        options: >-
          --name stoneflow-mysql
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      # 1️⃣  Pull the repository
      - name: Check out code
        uses: actions/checkout@v4

      # 2️⃣  Install PHP 8.2 + required tools/extensions
      - name: Set up PHP 8.2
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          coverage: none
          tools: composer, phpunit, wp-cli
          extensions: >
            mbstring,
            intl,
            dom,
            xml,
            simplexml,
            xmlwriter,
            curl,
            tokenizer,
            zip

      # 3️⃣  Install Composer dependencies (PHPUnit, WPCS, etc.)
      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --no-suggest

      # 4️⃣  Download WordPress core + official test library
      - name: Set up WordPress test library
        uses: sjinks/setup-wordpress-test-library@v2.1.4
        with:
          wordpress-version: latest

      # 5️⃣  Run the PHPUnit test suite
      - name: Run PHPUnit
        run: vendor/bin/phpunit --configuration phpunit.xml.dist --testdox

      # 6️⃣  Enforce WordPress coding standards
      - name: Run PHPCS
        run: vendor/bin/phpcs --standard=WordPress stoneflow
