name: StoneFlow WP-CLI Setup

on: [push, pull_request]

jobs:
  wpcli-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: wordpress_test
          MYSQL_USER: root
          MYSQL_PASSWORD: ''
          MYSQL_ROOT_PASSWORD: ''
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - name: Install WP-CLI
        run: |
          curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
          chmod +x wp-cli.phar
          sudo mv wp-cli.phar /usr/local/bin/wp

      - name: Set up WordPress
        run: |
          mkdir wp-test
          cd wp-test
          wp core download
          wp config create --dbname=wordpress_test --dbuser=root --dbpass= --dbhost=127.0.0.1 --skip-check
          wp db create
          wp core install --url="http://example.com" --title="Test Site" \
            --admin_user=admin --admin_password=admin --admin_email=test@example.com
          wp plugin install ../stoneflow-plugin --activate
